# Generated by Django 6.0.2 on 2026-02-20 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_role_parentteachermessage_studentfreetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloadsettings',
            name='class_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workload_settings', to='core.class'),
        ),
    ]
