# Generated by Django 5.2.6 on 2026-02-21 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parentstudentlink_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousStudentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('bullying', 'Bullying by student'), ('teacher_rude', 'Teacher rude behavior'), ('lesson_difficulty', 'Difficulty understanding teacher lessons'), ('other', 'Other concern')], max_length=30)),
                ('target_role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('unknown', 'Not sure')], default='unknown', max_length=20)),
                ('reported_person', models.CharField(blank=True, help_text='Optional name/identifier of teacher or student.', max_length=150)),
                ('class_section_info', models.CharField(blank=True, help_text='Optional class/section information.', max_length=120)),
                ('details', models.TextField(help_text='Describe what happened.')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='parentstudentlink',
            options={'ordering': ['-is_primary', '-requested_at']},
        ),
    ]
