# Generated by Django 5.2.6 on 2026-02-21 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_anonymousstudentreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='points_wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points', 'student__username'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('approval_bonus', 'Approval Bonus'), ('missed_homework', 'Missed Homework Penalty'), ('manual_adjustment', 'Manual Adjustment')], max_length=30)),
                ('points', models.IntegerField(help_text='Positive or negative points delta')),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_points_transactions', to=settings.AUTH_USER_MODEL)),
                ('homework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='core.homework')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('student', 'homework', 'transaction_type'), name='unique_points_tx_per_homework_type')],
            },
        ),
    ]
