# Generated by Django 5.2.6 on 2026-02-21 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_class_id_alter_homework_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymousstudentreport',
            name='is_anonymous',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anonymousstudentreport',
            name='reporter',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
