# Generated by Django 5.2.6 on 2026-02-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_anonymousstudentreport_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='submission_mode',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'In Person / Physical Copy')], default='online', max_length=20),
        ),
    ]
