# Generated by Django 5.2.6 on 2026-02-22 05:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_homeworksubmission_submission_mode_alter_class_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworksubmission',
            name='quiz_points_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('approval_bonus', 'Approval Bonus'), ('missed_homework', 'Missed Homework Penalty'), ('quiz_bonus', 'Quiz Correct Answer Bonus'), ('manual_adjustment', 'Manual Adjustment')], max_length=30),
        ),
        migrations.CreateModel(
            name='HomeworkQuizQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('points', models.PositiveIntegerField(default=5, help_text='Maximum 15 points per question.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)])),
                ('order', models.PositiveIntegerField(default=1)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='core.homework')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkQuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('awarded_points', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='core.homeworksubmission')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.homeworkquizquestion')),
            ],
            options={
                'ordering': ['question__order', 'id'],
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
